Module 1: Project 3 - Contact Form
PraisesPJMT/Portfolio-Project pull request #4
Opened 2022-07-05 17:53 UTC by PraisesPJMT

# Project 3: Contact Form

## Project Requirements
- Made sure that:
  - Name field accepts up to 30 chars.
  - Email field accepts only emails.
  - Message field accepts up to 500 chars.
  - All fields have placeholder text.
  - All fields have the correct type.
  - A user cannot submit the form if one or more of the fields is empty.
- Collect data using my account from the [Formspree service](https://formspree.io/html).
- In order to lay out the elements on the page,  I  used Flexbox.
- I stuck to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
- I implemented all button interactions (enable, hover, etc.).

2022-07-05 19:17 UTC, HAMMAS-SALEEM requested changes
## Required Changes :recycle:

### Hey Team (@PraisesPJMT, @mj-e-boc, @kessio) :wave:

### Highlights :1st_place_medal:

Linters are green :heavy_check_mark: 
Good implementation of validations :heavy_check_mark:
Most Design is very good :heavy_check_mark:


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

# Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 19:17 UTC, HAMMAS-SALEEM commented on index.html
> +                </form>
### Your Form Response

![formspree-error](https://user-images.githubusercontent.com/93039359/177396787-8c2c35e6-49be-4538-b148-9aa6a414d2a0.png)

- [ ]  Your form is not working. Please fix this by adding **name** attributes in your input fields. :+1:

2022-07-05 19:17 UTC, HAMMAS-SALEEM commented on index.html
>      </footer>
### You Footer
![footer (copy)](https://user-images.githubusercontent.com/93039359/177398770-a4ccc6bd-d6e9-4229-91f5-19c75f7accdc.png)
### Figma Footer
![Figma](https://user-images.githubusercontent.com/93039359/177398792-ca01591f-cea3-4fa5-81bd-51ccfda7d5c4.png)

- [ ] You can see that in your design, you have margins on left and right sides. Please remove these margins :+1:

2022-07-06 08:55 UTC, PraisesPJMT commented on index.html
> +            <div class="contact-form-container">
Oh Yes! I set a fixed width for the whole "body" that's why margins get to appear at the edges.
I just removed that.

I also did not notice the background colour for the "Contact Section".
I just made the necessary corrections.

Thanks so much.

2022-07-06 08:56 UTC, PraisesPJMT commented on index.html
> +                </form>
Oh yes! We discussed this during the paired programming session. We totally did not include it. 
We just made the additions.
Thanks.

2022-07-06 08:58 UTC, PraisesPJMT commented on index.html
>      </footer>
The footer margin was also affected by the fixed-width attribute of the "body".
We just made the necessary corrections.

Thanks:

2022-07-06 09:13 UTC, prolajumokeoni approved these changes
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 09:39 UTC, merged